# Generated by Django 4.0 on 2022-01-04 18:05
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(verbose_name='expiry date')),
            ],
        ),
    ]
