# Generated by Django 4.0 on 2022-01-04 18:09
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptranspile_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
