# Generated by Django 4.0 on 2022-01-04 18:14
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptranspile_auth', '0002_remove_usersession_id_usersession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_token',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
