# Generated by Django 4.0 on 2022-01-04 20:07
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptranspile_auth', '0003_usersession_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='userid',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
